[package]
name = "reconciliation-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web framework
actix-web = "4.4"
actix-multipart = "0.6"
actix-web-actors = "4.2"

# Async runtime
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Database
diesel = { version = "2.0", features = ["postgres", "chrono", "uuid", "numeric", "r2d2"] }
diesel_migrations = "2.0"
diesel_derives = "2.0"

# Additional dependencies
regex = "1.0"
bigdecimal = { version = "0.4", features = ["serde"] }
semver = "1.0"
chrono-tz = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
lazy_static = "1.4"
base64 = "0.21"

# Authentication & Security
jsonwebtoken = "9.0"
bcrypt = "0.15"
argon2 = "0.5"
rand = "0.8"

# UUID
uuid = { version = "1.0", features = ["v4", "serde"] }

# Date/Time
chrono = { version = "0.4", features = ["serde"] }

# HTTP client
reqwest = { version = "0.11", features = ["json"] }

# Redis
redis = { version = "0.23", features = ["tokio-comp"] }

# File handling
csv = "1.2"
sha2 = "0.10"

# Logging
env_logger = "0.10"
log = "0.4"

# Monitoring
prometheus = "0.13"

# Validation
validator = { version = "0.16", features = ["derive"] }

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Configuration
config = "0.13"
dotenv = "0.15"

# WebSocket
actix = "0.13"

# Testing
#[dev-dependencies]
#tokio-test = "0.4"