openapi: 3.0.0
info:
  title: Reconciliation Backend API
  version: 1.0.0
  description: Enterprise-grade reconciliation platform API
servers:
  - url: http://localhost:8080/api
paths:
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: List of users

