apiVersion: apps/v1
kind: Deployment
metadata:
  name: reconciliation-platform
  labels:
    app: reconciliation-platform
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reconciliation-platform
  template:
    metadata:
      labels:
        app: reconciliation-platform
        version: v1.0.0
    spec:
      containers:
      - name: frontend
        image: reconciliation-platform-frontend:latest
        ports:
        - containerPort: 1000
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api_url
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 1000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 1000
          initialDelaySeconds: 10
          periodSeconds: 5
      - name: backend
        image: reconciliation-platform-backend:latest
        ports:
        - containerPort: 2000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database_url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt_secret
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis_url
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 2000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 2000
          initialDelaySeconds: 10
          periodSeconds: 5

