# Alert Rules for Prometheus
# Triggers based on performance thresholds

groups:
  - name: reconciliation_alerts
    interval: 30s
    rules:
      # Uptime / CFUR Alert
      - alert: LowUptime
        expr: (sum(rate(http_requests_total[5m])) / count(http_requests_total)) < 0.998
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Uptime below 99.8%"
          description: "The application uptime has dropped below 99.8% (CFUR). Current value: {{ $value }}"
      
      # Latency Alert
      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "API latency exceeded 500ms"
          description: "p95 latency is {{ $value }}s (>500ms threshold)"
      
      # Error Rate Alert
      - alert: HighErrorRate
        expr: rate(http_errors_total[1m]) / rate(http_requests_total[1m]) > 0.01
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Error rate exceeded 1%"
          description: "Current error rate: {{ $value | humanizePercentage }}"

