---
# Kubernetes Deployment for 378 Reconciliation Platform Backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reconciliation-backend
  namespace: production
  labels:
    app: reconciliation-backend
    version: v1.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: reconciliation-backend
  template:
    metadata:
      labels:
        app: reconciliation-backend
        version: v1.0.0
    spec:
      serviceAccountName: reconciliation-backend
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: backend
        image: reconciliation-backend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 2000
          protocol: TCP
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: reconciliation-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: reconciliation-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: reconciliation-secrets
              key: jwt-secret
        - name: ENVIRONMENT
          value: "production"
        - name: ENABLE_AUTOMATED_BACKUPS
          value: "true"
        - name: BACKUP_S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: reconciliation-secrets
              key: backup-s3-bucket
        - name: AWS_REGION
          value: "us-east-1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      terminationGracePeriodSeconds: 30
---
# Service for backend
apiVersion: v1
kind: Service
metadata:
  name: reconciliation-backend
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: reconciliation-backend
  ports:
  - name: http
    port: 2000
    targetPort: http
    protocol: TCP
---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reconciliation-backend-hpa
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reconciliation-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30

