name: Governance Runner

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * *'

jobs:
  run-governance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install cargo-audit
        run: cargo install cargo-audit || true

      - name: Install frontend deps
        run: npm ci

      - name: Dependency scan
        run: bash scripts/security_audit.sh

      - name: Unit tests (backend)
        run: |
          cd backend
          cargo test --all --locked

      - name: Unit tests (frontend)
        run: npm test -- --ci

      - name: Build backend
        run: |
          cd backend
          cargo build --release --locked

      - name: Build frontend
        run: npm run build

      - name: Benchmark (k6)
        if: always()
        uses: grafana/k6-action@v0.3.1
        with:
          filename: load-test/k6-reconciliation.js
        env:
          BASE_URL: http://localhost:2000/api


